### ISSUE TITLE
Remove non-editing teacher does not remove the supervisor

### ISSUE THREAD

**Issue by rogerbaba** [BLC-HTWChur/moodle-mod_groupselect#1]
when removing a non-editing teacher or the role of the user have been changed the user still appears in the overview as a non editing teacher-
-> update table on view view.php and remove the user as non-editing teacher.

**Comment by phish108** [comment]
This could be related to the automatic selection function

**Comment by rogerbaba** [comment]
The supervisor should stay as the supervisor even if he got another role in the course

**Comment by rogerbaba** [comment]
remove the supervisor if he got unenrolled from the course => implement an event observer.
