### ISSUE TITLE
Omit calling require_once ($CFG->dirroot . '/lib/password_compat/lib/password.php');

### ISSUE THREAD

**Issue by lucaboesch** [BLC-HTWChur/moodle-mod_groupselect#10]
Dear Roger

You can omit calling require_once ($CFG->dirroot . '/lib/password_compat/lib/password.php'); in view.php

It throws a

PHP Notice:  password_compat is now standard in all versions of PHP that Moodle supports. You no longer need to include the lib/password_compat/lib/password.php
line 29 of /lib/password_compat/lib/password.php: call to debugging()
line 27 of /mod/groupselect/view.php: call to require_once()
in …/moodle/lib/weblib.php on line 3095

Best regards!

**Comment by phish108** [comment]
fixed
